inherit: true
build:
  dependencies:
    before:
      - phpenv rehash
      - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
      - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
      - cd ~/builds/ss
  tests:
    override:
      -
        command: vendor/bin/phpunit -c shop/phpunit.xml.dist --coverage-clover shop/coverage.xml
        coverage:
          file: shop/coverage.xml
          format: php-clover

tools:
  external_code_coverage: false
#  external_code_coverage:
#    enabled: true
#    timeout: 2500
#    runs: 3
  php_analyzer:
    enabled: true
#    config:
#      phpunit_checks:
#        enabled: true
  php_mess_detector:
    config:
      unused_code_rules:
        unused_private_field:  false
        unused_local_variable:  true
        unused_private_method:  true
        unused_formal_parameter:  true
      code_size_rules:
        npath_complexity:     true
        excessive_method_length:  true
        excessive_class_length:  true
        excessive_parameter_list:  true
        excessive_public_count:  true
        too_many_fields:      true
        too_many_methods:     true
        excessive_class_complexity:  true

