language: php
php:
- 5.3
before_script:

# get core code
- cd ~/builds
- git clone git://github.com/silverstripe/silverstripe-installer.git ss
- git clone git://github.com/silverstripe/sapphire.git ss/sapphire
- cd ss/sapphire
- git checkout 3.0.3
- cd ~/builds
- git clone git://github.com/silverstripe/silverstripe-cms.git ss/cms
- cd ss/cms
- git checkout 3.0.3
- cd ~/builds
- git clone git://github.com/burnbright/silverstripe-payment.git ss/payment
- cd ss/payment
- git checkout ss3
- cd ~/builds
- git clone git://github.com/burnbright/silverstripe-bootstrap.git ss/themes/bootstrap
- git clone git://github.com/burnbright/silverstripe-bootstrap-shop.git ss/themes/bootstrap_shop
- git clone https://github.com/silverstripe-labs/silverstripe-sqlite3.git ss/sqlite

- mv burnbright/silverstripe-shop ss/shop

# copy configs
- mv -f ss/shop/tests/travis/_config.php.travis ss/mysite/_config.php
- mv -f ss/shop/tests/travis/_ss_environment.php.travis ss/_ss_environment.php
- mv -f ss/shop/tests/travis/phpunit.xml.travis ss/phpunit.xml

#- ss/sapphire/sake dev/build "flush=all"

script:
- cd ~/builds/ss
- sapphire/sake dev/tests/module/shop