name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_require_extra:
        phpunit/phpunit:^9.5
        silverstripe/silverstripe-omnipay:dev-main
        php-http/discovery:^1.19.4
        symfony/http-foundation:^6.4.4
        moneyphp/money:^4.5.0
